
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Update github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: rhygg
          template: classic
          base: activity, community, repositories, metadata
          config_twemoji: yes
          repositories: 250
          plugin_notable: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: https://open.spotify.com/playlist/2syDAYRvmq65fGYUChN8rK?theme=0
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs
          plugin_wakatime_limit: 4
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: rhygg
